# Generated by Django 4.2.4 on 2023-08-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="assigned_tasks",
            field=models.ManyToManyField(to="tasks.task"),
        ),
    ]
