# Generated by Django 4.2.4 on 2023-08-17 00:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_assigned_tasks"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="assigned_tasks",
            new_name="tasks",
        ),
    ]
