[tool.isort]
skip = ["migrations", "venv"]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
profile = "black"

[tool.black]
line-length = 88
exclude = '''
/(
    \.git
  | venv
  | migrations
)/
'''
