name: Tests
on:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Create .env File
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Lint Code
        run: |
          black --check .
          isort --check .

      - name: Check Migrations
        run: python manage.py makemigrations --check

      - name: Run Tests
        run: pytest .
